services:
  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      # - "8888:8888" # Metrics exposed by the collector itself
      # - "8889:8889" # Metrics expored by Prometheus exporter
      - "4317:4317" # OTLP gRPC receiver

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686" # Jaeger UI

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090" # Prometheus UI
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000" # Grafana UI
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
